In [76]:
def first_10_word(text):
    return " ".join(text.split()[:10])

In [77]:
import pandas as pd 
from build_dataset import df

sample=df.sample(n=10,random_state=42)
df1=pd.DataFrame({
    "id":range(1,11),
    "Title":sample["Title"].values,
    "Category":sample["Category"].values,
    "Body":sample["Body"].apply(first_10_word)
})
df1

,id,Title,Category,Body
1782,1,"بالفيديو: سامي سعيد يطرح ''فرصة ومناسبة""",ثقافة,أطلق الفنان سامي سعيد أغنيته الشبابية الجديدة ...
3917,2,نجم الرجاء في لائحة المنتخب الوطني لكأس إفريقيا,رياضة,اختار هيرفي رونار، مدرب المنتخب الوطني، بدر با...
221,3,هذه طرق دفع التبرعات لصندوق تدبير جائحة كورونا,اقتصاد,أفادت وزارة الاقتصاد والمالية وإصلاح الإدارة ب...
2135,4,"60 دولة إفريقية تطالب ترامب بـ""الاعتذار""",دولي,طالب سفراء ازيد من 60 دولة إفريقية بالأمم المت...
5224,5,12 عمرة لموظفات إدارة السجون لهذا السبب,مجتمع,أجرت مندوبية العامة لإدارة السجون وإعادة الإدم...
1168,6,بالفيديو: هذا قائمة أشهر 5 أغانٍ عربية اقتبسها...,ثقافة,عادة ما نسمع ونشاهد أغاني وفيديو كليبات عربية ...
879,7,الجزائر تتصدر قائمة مخابئ الأموال إفريقيا.. وا...,اقتصاد,"كشفت ""شبكة العدالة الضريبية"" غير الحكومية ""Tax..."
156,8,الأسر المغربية تودع السنة بـ350 مليار من القروض,اقتصاد,تودع الأسر المغربية السنة الجارية وهي مثقلة با...
1657,9,بالفيديو: كونغولية تنافس حسناوات المغرب على لق...,ثقافة,خلقت المشاركة من الكونغو الديموقراطية، الحدث، ...
323,10,بالصور: طرام البيضاء يعقم عرباته لمنع انتشار ف...,اقتصاد,"دفع انتشار فيروس كورونا ""كوفيد 19"" شركة ""كازا ..."

In [78]:
l=[category for category in df["Category"].sample(n=10,random_state=42)]
print(l)

['ثقافة', 'رياضة', 'اقتصاد', 'دولي', 'مجتمع', 'ثقافة', 'اقتصاد', 'اقتصاد', 'ثقافة', 'اقتصاد']

In [79]:
print(type(df["Category"]))

<class 'pandas.Series'>

In [80]:
sample=df.sample(n=10,random_state=42)[["Title","Category"]]
print(type(sample.values))
print(type(sample))

<class 'numpy.ndarray'>
<class 'pandas.DataFrame'>

In [81]:
import pandas as pd

data = {
    "CustomerID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
                   1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1020],

    "First_Name": ["Frodo", "Abed", "Walter", "Dwight", "Jon", "Ron", "Jeff", "Sherlock",
                   "Gandalf", "Peter", "Samwise", "Harry", "Don", "Leslie", "Toby",
                   "Ron", "Michael", "Clark", "Creed", "Anakin", "Anakin"],

    "Last_Name": ["Baggins", "Nadir", "/White", "Schrute", "Snow", "Swanson", "Winger",
                  "Holmes", "", "Parker5", "Gamgee", "...Potter", "Draper", "Knope",
                  "Flenderson_", "Weasley", "Scott", "Kent", "Braton", "Skywalker",
                  "Skywalker"],

    "Phone_Number": ["123-545-5421", "123/643/9775", "7066950392", "123-543-2345",
                     "876|678|3469", "304-762-2467", "", "876|678|3469", "N/a",
                     "123-545-5421", "", "7066950392", "123-543-2345", "876|678|3469",
                     "304-762-2467", "123-545-5421", "123/643/9775", "7066950392",
                     "N/a", "876|678|3469", "876|678|3469"],

    "Address": [
        "123 Shire Lane, Shire",
        "93 West Main Street",
        "298 Drugs Driveway",
        "980 Paper Avenue, Pennsylvania, 18503",
        "123 Dragons Road",
        "768 City Parkway",
        "1209 South Street",
        "98 Clue Drive",
        "123 Middle Earth",
        "25th Main Street, New York",
        "612 Shire Lane, Shire",
        "2394 Hogwarts Avenue",
        "2039 Main Street",
        "343 City Parkway",
        "214 HR Avenue",
        "2395 Hogwarts Avenue",
        "121 Paper Avenue, Pennsylvania",
        "3498 Super Lane",
        "N/a",
        "910 Tatooine Road, Tatooine",
        "910 Tatooine Road, Tatooine"
    ],

    "Paying Customer": ["Yes", "No", "N", "Yes", "Y", "Yes", "No", "N", "Yes", "Yes",
                        "Yes", "Y", "Yes", "Yes", "N", "No", "Yes", "Y", "N/a", "Yes", "Yes"],

    "Do_Not_Contact": ["No", "Yes", "", "Y", "No", "Yes", "No", "No", "", "No",
                       "No", "", "N", "No", "No", "N", "No", "", "Yes", "N", "N"],

    "Not_Useful_Column": [True, False, True, True, True, True, False, False, False,
                          True, True, True, False, False, False, False, False, True,
                          True, True, True]
}

df = pd.DataFrame(data)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,,False
9,1010,Peter,Parker5,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [82]:
df = df.drop_duplicates()

In [83]:
df = df.drop(columns="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,
9,1010,Peter,Parker5,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [84]:
# df["Last_Name"] = df["Last_Name"].str.(l/r)strip("1235.../")
df["Last_Name"] = df["Last_Name"].str.strip("1235.../_")
df["Last_Name"]

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: str

In [85]:
# df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]',"",regex=True)
df["Phone_Number"] = df["Phone_Number"].str.replace(r'\D',"",regex=True)
df["Phone_Number"]=df["Phone_Number"].apply(lambda x:x[0:3]+'-'+x[3:6]+'-'+x[6:])
df["Phone_Number"] = df["Phone_Number"].str.replace("--","")
df["Phone_Number"]

0     123-545-5421
1     123-643-9775
2     706-695-0392
3     123-543-2345
4     876-678-3469
5     304-762-2467
6
7     876-678-3469
8
9     123-545-5421
10
11    706-695-0392
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17    706-695-0392
18
19    876-678-3469
Name: Phone_Number, dtype: str

In [86]:
df[["Street","State","Zip"]]=df["Address"].str.split(',',n=2,expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN
8,1009,Gandalf,,,123 Middle Earth,Yes,,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

In [87]:
df["Paying Customer"] = df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"] = df["Paying Customer"].str.replace("No","N")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("Yes","Y")
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace("No","N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN

In [88]:
df = df.replace("N/a","")

df.fillna("")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [89]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"] == "Y":
        df.drop(x,inplace = True)
for x in df.index:
    if df.loc[x,"Phone_Number"] == "":
        df.drop(x,inplace = True)

# or we can just do :
# df.dropna(subset="Phone_Number",inplace=True)

for x in df.index:
    if df.loc[x,"Do_Not_Contact"] != "N":
        df.loc[x,"Do_Not_Contact"]="N"

df
# numbers_to_call = df[df["Do_Not_Contact"] !="Y"]
# numbers_to_call=numbers_to_call[numbers_to_call["Phone_Number"]!=""]
# numbers_to_call

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,N,298 Drugs Driveway,NaN,NaN
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,N,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,N,3498 Super Lane,NaN,NaN
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN

In [ ]:
df.reset_index(drop=True,inplace=True)
df[""]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zip
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,NaN
1,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,N,298 Drugs Driveway,NaN,NaN
2,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN
3,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN
4,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,NaN
5,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,N,2394 Hogwarts Avenue,NaN,NaN
6,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,NaN,NaN
7,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,NaN,NaN
8,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN
9,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,NaN,NaN
10,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,NaN
11,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,N,3498 Super Lane,NaN,NaN
12,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,NaN