In [ ]:
import pandas as pd
df = pd.read_csv("../donnees/Le360.com.csv")
df

,Title,Body,Category
0,محللون: هل تخرج قوانين الاتحاد الإفريقي البرلم...,بعد مصادقة المجلس الوزاري، أمس، على القانون ال...,Policy
1,ساجد يغازل أخنوش: تحالفنا مع الأحرار متين ومسؤول,وصف الأمين العام لحزب الاتحاد الدستوري، محمد س...,Policy
2,ساجد يدعو إلى تكوين فريق موحد مع الأحرار بمجلس...,دعا الأمين العام لحزب الاتحاد الدستوري، محمد س...,Policy
3,أخنوش: على البرلمان الخروج من عطلته وانا راجل ...,قطع عزيز أخنوش، رئيس حزب التجمع الوطني للأحرار...,Policy
4,"كتائب ""البيجيدي"" تهاجم عمدة طنجة بسبب إلياس ال...",وجهت بعض كتائب حزب العدالة والتنمية في المغرب ...,Policy
...,...,...,...
144690,أستراليا ونيوزيلندا إلى نهائي كأس العالم للركبي,تأهل كل من المنتخب الأسترالي والنيوزيلندي إلى ...,Sport
144691,منتخب النيوزيلندا يتوج بكأس العالم للركبي,توج منتخب نيوزيلندا للمرة الثانية على التوالي ...,Sport
144692,الجديدة تحتضن تصفيات أولمبياد ريو,تحتضن مدينة الجديدة من 4 الى 9 نونبر الجاري من...,Sport
144693,منتخب كرة الطائرة الشاطئية يبحث عن التأهل إلى ...,ستكون مدينة الجديدة، على موعد مع منافسات إقصائ...,Sport
144694,الكانوي كاياك يهدي المغرب تذكرة حضور ثالثة للأ...,استطاعت البطلة المغربية هند الجميلي، التأهل إل...,Sport

In [20]:
category_mapping = {
    "Business": "اقتصاد",
    "Culture": "ثقافة",
    "International": "دولي",
    "Sport": "رياضة",
    "Policy": "سياسة",
    "Society": "مجتمع",
}

Keep only the six PFA categories

In [21]:
df = df[df["Category"].isin(category_mapping)]
df

,Title,Body,Category
0,محللون: هل تخرج قوانين الاتحاد الإفريقي البرلم...,بعد مصادقة المجلس الوزاري، أمس، على القانون ال...,Policy
1,ساجد يغازل أخنوش: تحالفنا مع الأحرار متين ومسؤول,وصف الأمين العام لحزب الاتحاد الدستوري، محمد س...,Policy
2,ساجد يدعو إلى تكوين فريق موحد مع الأحرار بمجلس...,دعا الأمين العام لحزب الاتحاد الدستوري، محمد س...,Policy
3,أخنوش: على البرلمان الخروج من عطلته وانا راجل ...,قطع عزيز أخنوش، رئيس حزب التجمع الوطني للأحرار...,Policy
4,"كتائب ""البيجيدي"" تهاجم عمدة طنجة بسبب إلياس ال...",وجهت بعض كتائب حزب العدالة والتنمية في المغرب ...,Policy
...,...,...,...
144690,أستراليا ونيوزيلندا إلى نهائي كأس العالم للركبي,تأهل كل من المنتخب الأسترالي والنيوزيلندي إلى ...,Sport
144691,منتخب النيوزيلندا يتوج بكأس العالم للركبي,توج منتخب نيوزيلندا للمرة الثانية على التوالي ...,Sport
144692,الجديدة تحتضن تصفيات أولمبياد ريو,تحتضن مدينة الجديدة من 4 الى 9 نونبر الجاري من...,Sport
144693,منتخب كرة الطائرة الشاطئية يبحث عن التأهل إلى ...,ستكون مدينة الجديدة، على موعد مع منافسات إقصائ...,Sport
144694,الكانوي كاياك يهدي المغرب تذكرة حضور ثالثة للأ...,استطاعت البطلة المغربية هند الجميلي، التأهل إل...,Sport


Translate categories into the PFA labels

In [22]:
df["Category"] = df["Category"].map(category_mapping)
df

,Title,Body,Category
0,محللون: هل تخرج قوانين الاتحاد الإفريقي البرلم...,بعد مصادقة المجلس الوزاري، أمس، على القانون ال...,سياسة
1,ساجد يغازل أخنوش: تحالفنا مع الأحرار متين ومسؤول,وصف الأمين العام لحزب الاتحاد الدستوري، محمد س...,سياسة
2,ساجد يدعو إلى تكوين فريق موحد مع الأحرار بمجلس...,دعا الأمين العام لحزب الاتحاد الدستوري، محمد س...,سياسة
3,أخنوش: على البرلمان الخروج من عطلته وانا راجل ...,قطع عزيز أخنوش، رئيس حزب التجمع الوطني للأحرار...,سياسة
4,"كتائب ""البيجيدي"" تهاجم عمدة طنجة بسبب إلياس ال...",وجهت بعض كتائب حزب العدالة والتنمية في المغرب ...,سياسة
...,...,...,...
144690,أستراليا ونيوزيلندا إلى نهائي كأس العالم للركبي,تأهل كل من المنتخب الأسترالي والنيوزيلندي إلى ...,رياضة
144691,منتخب النيوزيلندا يتوج بكأس العالم للركبي,توج منتخب نيوزيلندا للمرة الثانية على التوالي ...,رياضة
144692,الجديدة تحتضن تصفيات أولمبياد ريو,تحتضن مدينة الجديدة من 4 الى 9 نونبر الجاري من...,رياضة
144693,منتخب كرة الطائرة الشاطئية يبحث عن التأهل إلى ...,ستكون مدينة الجديدة، على موعد مع منافسات إقصائ...,رياضة
144694,الكانوي كاياك يهدي المغرب تذكرة حضور ثالثة للأ...,استطاعت البطلة المغربية هند الجميلي، التأهل إل...,رياضة

Categories:

In [23]:
df["Category"].value_counts()

Category
رياضة     50692
مجتمع     33594
سياسة     14351
اقتصاد     6220
دولي       5382
ثقافة      3668
Name: count, dtype: int64

Select 1000 articles from each category:

In [25]:
samples = []

for category in category_mapping.values():

    category_articles = df[df["Category"] == category]

    sample = category_articles.sample(
        n=3500,
        random_state=42
    )

    samples.append(sample)

df = pd.concat(samples, ignore_index=True)
df

,Title,Body,Category
0,وفد فرنسي يزور وجدة لتدارس مشروع الطاقة المستدامة,يزور وفد من ليل الفرنسية مدينة وجدة، منذ يوم ا...,اقتصاد
1,النعناع المستهلك بطنجة غير صالح وخطير على صحة ...,حملت مراسلة موجهة إلى كل من والي جهة طنجة تطوا...,اقتصاد
2,القباج: المغرب استطاع أن يحوز حصته من سوق السي...,أكد رئيس الكونفدرالية الوطنية للسياحة، عبد الل...,اقتصاد
3,"“دولي دول"" تحتفل ب 40 سنة من الرفاهية","احتفلت شركة ""دولي دول"" للأثاث والأفرشة، اليوم ...",اقتصاد
4,هذا ما كشفه تقرير مجلس جطو حول المقاولات العمومية,أوصى المجلس الأعلى للحسابات، في تقرير موضوعاتي...,اقتصاد
...,...,...,...
20995,بالفيديو: سلطات فاس تطلق حملة تحسيسية للوقاية ...,انطلقت مساء الثلاثاء 18 غشت 2020، حملة تحسيسية...,مجتمع
20996,البيضاء. فك لغز إصابة تلميذة قاصر بشفرة حلاقة,فكت مصالح الأمن بمنطقة أمن بنمسيك بالبيضاء، نه...,مجتمع
20997,768 مرشحا من نزلاء السجون يجتازون امتحانات الب...,أفادت المندوبية العامة لإدارة السجون وإعادة ال...,مجتمع
20998,مكناس. متهم بقتل والده بالسلاح الابيض,أوقفت مصالح ولاية أمن مكناس مساء اليوم الخميس ...,مجتمع
20999,"مجلس اليزمي والدرك الملكي يكونان حول ""الوقاية ...",انطلق منذ الأمس بالمدرسة الملكية لضباط الدرك ا...,مجتمع

Final category distribution and number of articles:

In [26]:
df["Category"].value_counts()
# len(df)

Category
اقتصاد    3500
ثقافة     3500
دولي      3500
رياضة     3500
سياسة     3500
مجتمع     3500
Name: count, dtype: int64

Rename the columns

In [27]:
df = df.rename(columns={
    "Title":"title",
    "Body":"body",
    "Category":'category'
})
df

,title,body,category
0,وفد فرنسي يزور وجدة لتدارس مشروع الطاقة المستدامة,يزور وفد من ليل الفرنسية مدينة وجدة، منذ يوم ا...,اقتصاد
1,النعناع المستهلك بطنجة غير صالح وخطير على صحة ...,حملت مراسلة موجهة إلى كل من والي جهة طنجة تطوا...,اقتصاد
2,القباج: المغرب استطاع أن يحوز حصته من سوق السي...,أكد رئيس الكونفدرالية الوطنية للسياحة، عبد الل...,اقتصاد
3,"“دولي دول"" تحتفل ب 40 سنة من الرفاهية","احتفلت شركة ""دولي دول"" للأثاث والأفرشة، اليوم ...",اقتصاد
4,هذا ما كشفه تقرير مجلس جطو حول المقاولات العمومية,أوصى المجلس الأعلى للحسابات، في تقرير موضوعاتي...,اقتصاد
...,...,...,...
20995,بالفيديو: سلطات فاس تطلق حملة تحسيسية للوقاية ...,انطلقت مساء الثلاثاء 18 غشت 2020، حملة تحسيسية...,مجتمع
20996,البيضاء. فك لغز إصابة تلميذة قاصر بشفرة حلاقة,فكت مصالح الأمن بمنطقة أمن بنمسيك بالبيضاء، نه...,مجتمع
20997,768 مرشحا من نزلاء السجون يجتازون امتحانات الب...,أفادت المندوبية العامة لإدارة السجون وإعادة ال...,مجتمع
20998,مكناس. متهم بقتل والده بالسلاح الابيض,أوقفت مصالح ولاية أمن مكناس مساء اليوم الخميس ...,مجتمع
20999,"مجلس اليزمي والدرك الملكي يكونان حول ""الوقاية ...",انطلق منذ الأمس بالمدرسة الملكية لضباط الدرك ا...,مجتمع

Create the id

In [28]:
df["id"]=[
    f"art-{i:04d}"
    for i in range(1,len(df)+1)
]
df

,title,body,category,id
0,وفد فرنسي يزور وجدة لتدارس مشروع الطاقة المستدامة,يزور وفد من ليل الفرنسية مدينة وجدة، منذ يوم ا...,اقتصاد,art-0001
1,النعناع المستهلك بطنجة غير صالح وخطير على صحة ...,حملت مراسلة موجهة إلى كل من والي جهة طنجة تطوا...,اقتصاد,art-0002
2,القباج: المغرب استطاع أن يحوز حصته من سوق السي...,أكد رئيس الكونفدرالية الوطنية للسياحة، عبد الل...,اقتصاد,art-0003
3,"“دولي دول"" تحتفل ب 40 سنة من الرفاهية","احتفلت شركة ""دولي دول"" للأثاث والأفرشة، اليوم ...",اقتصاد,art-0004
4,هذا ما كشفه تقرير مجلس جطو حول المقاولات العمومية,أوصى المجلس الأعلى للحسابات، في تقرير موضوعاتي...,اقتصاد,art-0005
...,...,...,...,...
20995,بالفيديو: سلطات فاس تطلق حملة تحسيسية للوقاية ...,انطلقت مساء الثلاثاء 18 غشت 2020، حملة تحسيسية...,مجتمع,art-20996
20996,البيضاء. فك لغز إصابة تلميذة قاصر بشفرة حلاقة,فكت مصالح الأمن بمنطقة أمن بنمسيك بالبيضاء، نه...,مجتمع,art-20997
20997,768 مرشحا من نزلاء السجون يجتازون امتحانات الب...,أفادت المندوبية العامة لإدارة السجون وإعادة ال...,مجتمع,art-20998
20998,مكناس. متهم بقتل والده بالسلاح الابيض,أوقفت مصالح ولاية أمن مكناس مساء اليوم الخميس ...,مجتمع,art-20999
20999,"مجلس اليزمي والدرك الملكي يكونان حول ""الوقاية ...",انطلق منذ الأمس بالمدرسة الملكية لضباط الدرك ا...,مجتمع,art-21000

In [29]:
df["categories"]=df["category"].apply(lambda x:[x])

In [30]:
import random
from datetime import date, timedelta

random.seed(42)

start_date = date(2024, 1, 1)
end_date = date(2026, 3, 31)

days_range = (end_date - start_date).days

df["publishedAt"] = [
    (start_date + timedelta(days=random.randint(0, days_range))).isoformat()
    for _ in range(len(df))
]
df=df[["id","title","body","categories","publishedAt"]]
df

,id,title,body,categories,publishedAt
0,art-0001,وفد فرنسي يزور وجدة لتدارس مشروع الطاقة المستدامة,يزور وفد من ليل الفرنسية مدينة وجدة، منذ يوم ا...,[اقتصاد],2025-10-16
1,art-0002,النعناع المستهلك بطنجة غير صالح وخطير على صحة ...,حملت مراسلة موجهة إلى كل من والي جهة طنجة تطوا...,[اقتصاد],2024-04-24
2,art-0003,القباج: المغرب استطاع أن يحوز حصته من سوق السي...,أكد رئيس الكونفدرالية الوطنية للسياحة، عبد الل...,[اقتصاد],2024-01-26
3,art-0004,"“دولي دول"" تحتفل ب 40 سنة من الرفاهية","احتفلت شركة ""دولي دول"" للأثاث والأفرشة، اليوم ...",[اقتصاد],2026-01-29
4,art-0005,هذا ما كشفه تقرير مجلس جطو حول المقاولات العمومية,أوصى المجلس الأعلى للحسابات، في تقرير موضوعاتي...,[اقتصاد],2024-10-08
...,...,...,...,...,...
20995,art-20996,بالفيديو: سلطات فاس تطلق حملة تحسيسية للوقاية ...,انطلقت مساء الثلاثاء 18 غشت 2020، حملة تحسيسية...,[مجتمع],2025-06-07
20996,art-20997,البيضاء. فك لغز إصابة تلميذة قاصر بشفرة حلاقة,فكت مصالح الأمن بمنطقة أمن بنمسيك بالبيضاء، نه...,[مجتمع],2025-02-01
20997,art-20998,768 مرشحا من نزلاء السجون يجتازون امتحانات الب...,أفادت المندوبية العامة لإدارة السجون وإعادة ال...,[مجتمع],2024-06-12
20998,art-20999,مكناس. متهم بقتل والده بالسلاح الابيض,أوقفت مصالح ولاية أمن مكناس مساء اليوم الخميس ...,[مجتمع],2024-07-25
20999,art-21000,"مجلس اليزمي والدرك الملكي يكونان حول ""الوقاية ...",انطلق منذ الأمس بالمدرسة الملكية لضباط الدرك ا...,[مجتمع],2026-02-11

Convert the DataFrame to JSON

In [31]:
data = df.to_dict(orient="records")

import json

with open(
    "../donnees/articles.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        data,
        f,
        ensure_ascii=False,
        indent=2
    )
df

,id,title,body,categories,publishedAt
0,art-0001,وفد فرنسي يزور وجدة لتدارس مشروع الطاقة المستدامة,يزور وفد من ليل الفرنسية مدينة وجدة، منذ يوم ا...,[اقتصاد],2025-10-16
1,art-0002,النعناع المستهلك بطنجة غير صالح وخطير على صحة ...,حملت مراسلة موجهة إلى كل من والي جهة طنجة تطوا...,[اقتصاد],2024-04-24
2,art-0003,القباج: المغرب استطاع أن يحوز حصته من سوق السي...,أكد رئيس الكونفدرالية الوطنية للسياحة، عبد الل...,[اقتصاد],2024-01-26
3,art-0004,"“دولي دول"" تحتفل ب 40 سنة من الرفاهية","احتفلت شركة ""دولي دول"" للأثاث والأفرشة، اليوم ...",[اقتصاد],2026-01-29
4,art-0005,هذا ما كشفه تقرير مجلس جطو حول المقاولات العمومية,أوصى المجلس الأعلى للحسابات، في تقرير موضوعاتي...,[اقتصاد],2024-10-08
...,...,...,...,...,...
20995,art-20996,بالفيديو: سلطات فاس تطلق حملة تحسيسية للوقاية ...,انطلقت مساء الثلاثاء 18 غشت 2020، حملة تحسيسية...,[مجتمع],2025-06-07
20996,art-20997,البيضاء. فك لغز إصابة تلميذة قاصر بشفرة حلاقة,فكت مصالح الأمن بمنطقة أمن بنمسيك بالبيضاء، نه...,[مجتمع],2025-02-01
20997,art-20998,768 مرشحا من نزلاء السجون يجتازون امتحانات الب...,أفادت المندوبية العامة لإدارة السجون وإعادة ال...,[مجتمع],2024-06-12
20998,art-20999,مكناس. متهم بقتل والده بالسلاح الابيض,أوقفت مصالح ولاية أمن مكناس مساء اليوم الخميس ...,[مجتمع],2024-07-25
20999,art-21000,"مجلس اليزمي والدرك الملكي يكونان حول ""الوقاية ...",انطلق منذ الأمس بالمدرسة الملكية لضباط الدرك ا...,[مجتمع],2026-02-11